name: basic_clean_arch
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # Dependency injection
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  
  # UI States
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  auto_route: ^5.0.4
  
  # Network Handlers
  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3

  easy_logger: ^0.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.4
  freezed: ^2.3.2
  auto_route_generator: ^5.0.3
  json_serializable: ^6.6.1

flutter_gen:
  output: lib/generated

flutter:


  uses-material-design: true
  
  assets:
    - assets/images/

